/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adbd_conmysq;

/**
 *
 * @author hilde
 */
public class FLogin extends javax.swing.JFrame {

    /**
     * Creates new form FLogin
     */
    public FLogin() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoContrase = new javax.swing.JLabel();
        TxtNombre1 = new javax.swing.JLabel();
        TxtNombre2 = new javax.swing.JLabel();
        cja_contraseña = new javax.swing.JPasswordField();
        logouser = new javax.swing.JLabel();
        cja_usuario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BntIniciarSesion = new javax.swing.JButton();
        TITULO = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fndNegro1 = new javax.swing.JLabel();
        fndNegro = new javax.swing.JLabel();
        wallpapper = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        esteSeCambiara = new javax.swing.JTextField();
        btnShowContra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoContrase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/contraLogo.png"))); // NOI18N
        getContentPane().add(logoContrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 30, 30));

        TxtNombre1.setFont(new java.awt.Font("Sitka Subheading", 2, 12)); // NOI18N
        TxtNombre1.setForeground(new java.awt.Color(102, 102, 102));
        TxtNombre1.setText("name user");
        getContentPane().add(TxtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 110, -1));

        TxtNombre2.setFont(new java.awt.Font("Sitka Subheading", 2, 12)); // NOI18N
        TxtNombre2.setForeground(new java.awt.Color(102, 102, 102));
        TxtNombre2.setText("password");
        getContentPane().add(TxtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 110, -1));

        cja_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cja_contraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(cja_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 320, 40));

        logouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/userLogo.png"))); // NOI18N
        getContentPane().add(logouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 30, 30));

        cja_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cja_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(cja_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 320, 40));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 350, 60));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        BntIniciarSesion.setText("LOGIN");
        BntIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(BntIniciarSesion);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 350, 40));

        TITULO.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        TITULO.setForeground(new java.awt.Color(255, 255, 255));
        TITULO.setText("LOGIN USERS");
        getContentPane().add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 260, 40));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 350, 90));

        fndNegro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FONDO NEGRO 50%.png"))); // NOI18N
        getContentPane().add(fndNegro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 500));

        fndNegro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/FONDO NEGRO 50%.png"))); // NOI18N
        getContentPane().add(fndNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 500));

        wallpapper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1020X500 FOND AZULOGO.png"))); // NOI18N
        getContentPane().add(wallpapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 340, 240));

        esteSeCambiara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esteSeCambiaraActionPerformed(evt);
            }
        });
        getContentPane().add(esteSeCambiara, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 320, 30));

        btnShowContra.setText("jButton1");
        btnShowContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowContraActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BntIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BntIniciarSesionActionPerformed

    private void esteSeCambiaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esteSeCambiaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esteSeCambiaraActionPerformed

    private void btnShowContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowContraActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnShowContraActionPerformed

    private void cja_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cja_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cja_usuarioActionPerformed

    private void cja_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cja_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cja_contraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntIniciarSesion;
    private javax.swing.JLabel TITULO;
    private javax.swing.JLabel TxtNombre1;
    private javax.swing.JLabel TxtNombre2;
    private javax.swing.JButton btnShowContra;
    private javax.swing.JPasswordField cja_contraseña;
    private javax.swing.JTextField cja_usuario;
    private javax.swing.JTextField esteSeCambiara;
    private javax.swing.JLabel fndNegro;
    private javax.swing.JLabel fndNegro1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logoContrase;
    private javax.swing.JLabel logouser;
    private javax.swing.JLabel wallpapper;
    // End of variables declaration//GEN-END:variables
}
